name: Build and Push Gromox Images

on:
  push:
    branches: [master]
    paths:
      - '**/Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/**'
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
    
jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push gromox-core
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/gromox-core:latest"
          docker build -t "$IMAGE" -f ./gromox-core/Dockerfile .
          docker push "$IMAGE"

      - name: Build and push gromox-archive
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/gromox-archive:latest"
          docker build -t "$IMAGE" -f ./gromox-archive/Dockerfile .
          docker push "$IMAGE"

      - name: Build and push gromox-office
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/gromox-office:latest"
          docker build -t "$IMAGE" -f ./gromox-office/Dockerfile .
          docker push "$IMAGE"
